apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
spec:
  selector:
    matchLabels:
      run: grpc-client
  replicas: 1
  template:
    metadata:
      labels:
        run: grpc-client
    spec:
      containers:
      - name: grpc-client
        image: msjikuma/grpcclient1:1
        env:
        - name: serverip
          value: "grpc-server"